# .streamlit/secrets.toml

SUPABASE_URL="https://lzlitfcxkbiwsomamqcx.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6bGl0ZmN4a2Jpd3NvbWFtcWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjIxNDMsImV4cCI6MjA2ODA5ODE0M30.VckCWiVw7_dYS0xZLz3OZ-VkmcZjTJG07NSgzK4OHac"
